import type { Exercise } from '../types';

export const DEFAULT_EXERCISES: Exercise[] = [
  // ─── KLATKA ────────────────────────────────────────────────────────────────
  {
    id: 'wyciskanie-sztangi',
    name: 'Wyciskanie sztangi na ławce poziomej',
    nameEn: 'Barbell Bench Press',
    category: 'klatka',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Połóż się na ławce, chwyć sztangę nieco szerzej niż szerokość barków. Opuść ją kontrolowanie do klatki piersiowej na poziomie brodawek, następnie wyciśnij do pełnego wyprostu ramion. Łokcie trzymaj pod kątem ok. 45–75° do tułowia.',
  },
  {
    id: 'wyciskanie-hantli-skos',
    name: 'Wyciskanie hantli na ławce skośnej',
    nameEn: 'Incline Dumbbell Press',
    category: 'klatka',
    equipment: 'hantle',
    isCustom: false,
    description: 'Ustaw ławkę pod kątem 30–45°. Trzymaj hantle na poziomie górnej części klatki, łokcie lekko poniżej barków. Wyciśnij hantle ku górze zbliżając je do siebie nad klatką, następnie opuść kontrolowanie.',
  },
  {
    id: 'wyciskanie-hantli-poziom',
    name: 'Wyciskanie hantli na ławce poziomej',
    nameEn: 'Flat Dumbbell Press',
    category: 'klatka',
    equipment: 'hantle',
    isCustom: false,
    description: 'Połóż się na poziomej ławce z hantlami na poziomie klatki piersiowej. Wyciśnij hantle ku górze, zbliżając je do siebie, nie doprowadzając do stykania się. Opuść powoli, czując rozciągnięcie w klatce.',
  },
  {
    id: 'rozpietki-hantlami',
    name: 'Rozpiętki hantlami',
    nameEn: 'Dumbbell Flyes',
    category: 'klatka',
    equipment: 'hantle',
    isCustom: false,
    description: 'Połóż się na ławce, trzymaj hantle nad klatką z lekko ugiętymi łokciami. Rozłóż ramiona na boki w szerokim łuku, czując rozciągnięcie klatki, następnie złącz je z powrotem, jakbyś obejmował duże drzewo.',
  },
  {
    id: 'pompki-porecze',
    name: 'Pompki na poręczach',
    nameEn: 'Chest Dips',
    category: 'klatka',
    equipment: 'wolny',
    isCustom: false,
    description: 'Chwyć poręcze i unieś się na wyprostowanych ramionach. Pochyl tułów lekko do przodu (ok. 15–30°), zegnij łokcie i opuść ciało aż poczujesz rozciągnięcie klatki. Wypchnij się do góry nie prostując całkowicie łokci na górze.',
  },
  {
    id: 'cable-crossover',
    name: 'Krzyżowanie linek',
    nameEn: 'Cable Crossover',
    category: 'klatka',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Ustaw linki wysoko (wariant górny) lub nisko (wariant dolny). Stań w rozkroku, chwyć uchwyty i ściągaj je przed siebie, krzyżując nadgarstki. Skup się na ściskaniu klatki w końcowej pozycji przez 1–2 sekundy.',
  },
  {
    id: 'push-up',
    name: 'Pompki',
    nameEn: 'Push-Up',
    category: 'klatka',
    equipment: 'wolny',
    isCustom: false,
    description: 'Połóż się przodem, dłonie nieco szerzej niż barki. Utrzymuj ciało w linii prostej od głowy do pięt. Opuść klatkę niemal do podłogi zginając łokcie, następnie wyciśnij się do góry.',
  },
  {
    id: 'chest-press-maszyna',
    name: 'Wyciskanie na maszynie (klatka)',
    nameEn: 'Machine Chest Press',
    category: 'klatka',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Ustaw siedzisko tak, by uchwyty były na poziomie środkowej klatki. Wyciśnij uchwyty do przodu do prawie pełnego wyprostu, następnie wróć kontrolowanie. Plecy trzymaj przy oparciu przez cały ruch.',
  },
  {
    id: 'incline-barbell-press',
    name: 'Wyciskanie sztangi na ławce skośnej',
    nameEn: 'Incline Barbell Press',
    category: 'klatka',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Ustaw ławkę pod kątem 30–45°. Chwyć sztangę nieco szerzej niż barki i opuść ją do górnej części klatki (ok. 2–3 cm poniżej obojczyków). Wyciśnij wybuchowo do góry, nie blokując łokci całkowicie.',
  },
  {
    id: 'decline-bench-press',
    name: 'Wyciskanie na ławce ujemnej',
    nameEn: 'Decline Bench Press',
    category: 'klatka',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Połóż się na ławce ze spadkiem (głowa poniżej bioder), zablokuj nogi. Opuść sztangę do dolnej części klatki, następnie wyciśnij. Angażuje głównie dolne włókna mięśnia piersiowego.',
  },
  {
    id: 'dumbbell-pullover',
    name: 'Pullover z hantlem',
    nameEn: 'Dumbbell Pullover',
    category: 'klatka',
    equipment: 'hantle',
    isCustom: false,
    description: 'Połóż się prostopadle do ławki, podpierając tylko górną część pleców. Trzymaj hantel oburącz nad klatką, następnie opuść go łukiem za głowę czując rozciągnięcie klatki i zębatych. Wróć do pozycji startowej.',
  },
  {
    id: 'pec-deck',
    name: 'Maszyna motylkowa',
    nameEn: 'Pec Deck',
    category: 'klatka',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Usiądź na maszynie, ustaw ramiona na podpórkach na poziomie barków z łokciami zgiętymi ok. 90°. Ściągnij ramiona do przodu, ściskając klatkę w środkowym punkcie. Wróć kontrolowanie nie przeciążając stawu barkowego.',
  },
  {
    id: 'low-cable-fly',
    name: 'Rozpiętki na wyciągu dolnym',
    nameEn: 'Low Cable Fly',
    category: 'klatka',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Ustaw linki w dolnej pozycji wyciągu. Stań między maszynami, chwyć uchwyty i unieś ramiona łukiem ku górze i do przodu, skupiając się na ściskaniu górnej części klatki. Trzymaj lekko ugięte łokcie przez cały ruch.',
  },
  {
    id: 'wide-push-up',
    name: 'Pompki szerokim chwytem',
    nameEn: 'Wide-Grip Push-Up',
    category: 'klatka',
    equipment: 'wolny',
    isCustom: false,
    description: 'Przyjmij pozycję pompki z dłońmi znacznie szerzej niż szerokość barków. Szeroki chwyt lepiej angażuje zewnętrzną część klatki. Opuść klatkę do podłogi i wypchnij ciało do góry utrzymując prostą sylwetkę.',
  },
  {
    id: 'svend-press',
    name: 'Wyciskanie Svenda',
    nameEn: 'Svend Press',
    category: 'klatka',
    equipment: 'wolny',
    isCustom: false,
    description: 'Stań lub usiądź, trzymaj talerz ze sztangi obiema dłońmi ściskając go mocno (to kluczowe). Wyciśnij talerz do przodu na wysokości klatki. Wróć powoli — ciągłe ściskanie talerza aktywuje klatki przez cały czas.',
  },
  {
    id: 'hex-press',
    name: 'Hex Press',
    nameEn: 'Hex Press',
    category: 'klatka',
    equipment: 'hantle',
    isCustom: false,
    description: 'Połóż się na ławce i ściśnij dwie hantle razem chwytając je równolegle (jak trzymasz kierownicę). Wyciśnij je do góry utrzymując wzajemny nacisk — to aktywuje mostki i środkową klatkę bardziej niż standardowe wyciskanie.',
  },

  // ─── KLATKA (dodatkowe) ─────────────────────────────────────────────────────
  {
    id: 'smith-bench-press',
    name: 'Wyciskanie na Smith Machine poziomo',
    nameEn: 'Smith Machine Bench Press',
    category: 'klatka',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Połóż się na ławce w maszynie Smitha. Sztanga porusza się po stałej prowadnicy. Chwyć szeroko, opuść do klatki piersiowej na poziomie brodawek, wyciśnij do pełnego wyprostu. Prowadnica odciąża stabilizatory, pozwalając skupić się na klatce.',
  },
  {
    id: 'smith-incline-bench-press',
    name: 'Wyciskanie na Smith Machine skos +',
    nameEn: 'Smith Machine Incline Bench Press',
    category: 'klatka',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Ustaw ławkę pod kątem 30–45° w maszynie Smitha. Opuść sztangę do górnej klatki (obojczyki), wyciśnij pionowo. Skupia się na górnej części klatki i przednich naramiennych. Prowadnica Smitha wymaga ustawienia ławki dokładnie pod trajektorią ruchu.',
  },
  {
    id: 'smith-decline-bench-press',
    name: 'Wyciskanie na Smith Machine skos −',
    nameEn: 'Smith Machine Decline Bench Press',
    category: 'klatka',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Ustaw ławkę z ujemnym nachyleniem w maszynie Smitha. Opuść sztangę do dolnej klatki. Skupia się na dolnej części klatki piersiowej. Zablokuj nogi i wyciśnij pionowo wzdłuż prowadnicy.',
  },
  {
    id: 'iso-lateral-chest-press',
    name: 'Wyciskanie klatki Iso Lateral',
    nameEn: 'Iso Lateral Chest Press Machine',
    category: 'klatka',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Maszyna Iso Lateral Chest Press z niezależnymi ramionami. Usiądź, plecy przy oparciu, uchwyty na poziomie środkowej klatki. Każde ramię pracuje niezależnie — wyrównuje siłę i zakres ruchu obu stron. Wyciśnij do przodu, nie blokując całkowicie łokci.',
  },
  {
    id: 'cable-fly-mid',
    name: 'Rozpiętki na wyciągu ustawionym na środku',
    nameEn: 'Cable Fly Mid',
    category: 'klatka',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Ustaw wyciągi na wysokości barków (środkowa pozycja). Chwyć uchwyty i ściągaj łukiem przed klatkę na poziomie mostka. Ruch krzyżuje się przed tułowiem. Angażuje środkową klatkę i zapewnia stałe napięcie w pełnym zakresie ruchu.',
  },

  // ─── PLECY ─────────────────────────────────────────────────────────────────
  {
    id: 'martwy-ciag',
    name: 'Martwy ciąg',
    nameEn: 'Deadlift',
    category: 'plecy',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Stań nad sztangą z stopami na szerokość bioder, palce pod drążkiem. Zegnij biodra i kolana, chwyć sztangę na szerokość barków, plecy proste. Napnij ciało i unieś sztangę, prostując nogi i biodra jednocześnie, zakończ w wyprostowanej pozycji.',
  },
  {
    id: 'wioslowanie-sztanga',
    name: 'Wiosłowanie sztangą',
    nameEn: 'Barbell Row',
    category: 'plecy',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Pochyl tułów do przodu ok. 45°, kolana lekko ugięte. Chwyć sztangę na szerokość barków i pociągnij ją do brzucha ściągając łopatki. Łokcie prowadź blisko tułowia. Opuść sztangę kontrolowanie do pełnego wyprostu ramion.',
  },
  {
    id: 'wioslowanie-hantel',
    name: 'Wiosłowanie hantlem jednostronnie',
    nameEn: 'Single-Arm Dumbbell Row',
    category: 'plecy',
    equipment: 'hantle',
    isCustom: false,
    description: 'Oprzyj jedno kolano i rękę na ławce. Drugą ręką chwyć hantel i pociągnij go do biodra, łokieć idzie prosto do góry i za tułów. Skup się na pracy łopatki — obróć ją do kręgosłupa na szczycie ruchu.',
  },
  {
    id: 'przyciaganie-wyciag',
    name: 'Przyciąganie drążka wyciągu górnego',
    nameEn: 'Lat Pulldown',
    category: 'plecy',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Usiądź przy wyciągu, uda pod poduszką. Chwyć drążek szerokim chwytem, lekko odchyl tułów. Pociągnij drążek do górnej klatki ściągając łopatki w dół i do tyłu. Nie huśtaj tułowiem — kontroluj ruch.',
  },
  {
    id: 'wioslowanie-maszyna',
    name: 'Wiosłowanie na maszynie',
    nameEn: 'Seated Cable Row',
    category: 'plecy',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Usiądź, stopy na podpórkach, kolana lekko ugięte. Chwyć uchwyt i pociągnij do brzucha ściskając łopatki ze sobą. Na chwilę przytrzymaj w końcowej pozycji. Wróć do wyprostu z kontrolą, czując rozciągnięcie pleców.',
  },
  {
    id: 'podciaganie',
    name: 'Podciąganie na drążku',
    nameEn: 'Pull-Up',
    category: 'plecy',
    equipment: 'wolny',
    isCustom: false,
    description: 'Chwyć drążek nachwytem nieco szerzej niż barki. Zacznij od zwisu z lekko napiętymi łopatkami. Pociągnij ciało do góry aż broda przekroczy drążek, ściągając łokcie w dół i do tyłu. Opuść się powoli.',
  },
  {
    id: 't-bar-row',
    name: 'Wiosłowanie T-bar',
    nameEn: 'T-Bar Row',
    category: 'plecy',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Stań okrakiem nad sztangą opartą w rogu lub na maszynie T-bar. Pochyl tułów do przodu, chwyć uchwyt i pociągnij ciężar do klatki, prowadząc łokcie po bokach ciała. Ściśnij łopatki na górze.',
  },
  {
    id: 'face-pull',
    name: 'Ściąganie do twarzy',
    nameEn: 'Face Pull',
    category: 'plecy',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Ustaw wyciąg na poziomie twarzy, chwyć linę uchwytem neutralnym. Ściągaj linę do twarzy/szyi rozchylając dłonie na zewnątrz. Łokcie trzymaj na poziomie uszu. Ćwiczenie wzmacnia tylne naramienne i rotatory.',
  },
  {
    id: 'wzruszanie-ramionami',
    name: 'Wzruszanie ramionami',
    nameEn: 'Shrug',
    category: 'plecy',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Stań z hantlami lub sztangą opuszczonymi wzdłuż ciała. Unieś barki prosto do góry, jakbyś chciał dotknąć nimi uszu. Nie obracaj ramionami w kółko. Przytrzymaj na górze 1 sekundę i opuść powoli.',
  },
  {
    id: 'straight-arm-pulldown',
    name: 'Ściąganie prostymi ramionami',
    nameEn: 'Straight-Arm Pulldown',
    category: 'plecy',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Stań przed wyciągiem górnym, chwyć drążek prostymi ramionami na wysokości klatki. Ściągaj drążek łukiem w dół, trzymając ramiona proste, angażując najszersze mięśnie grzbietu. Zatrzymaj przy udach i wróć.',
  },
  {
    id: 'chest-supported-row',
    name: 'Wiosłowanie z oparciem klatki',
    nameEn: 'Chest-Supported Row',
    category: 'plecy',
    equipment: 'hantle',
    isCustom: false,
    description: 'Oprzyj klatkę na pochylonej ławce (kąt 30–45°). Trzymaj hantle opuszczone prostopadle do ziemi. Pociągnij je do boków ciała ściskając łopatki. Oparcie eliminuje kołysanie i izoluje plecy.',
  },
  {
    id: 'rack-pull',
    name: 'Martwy ciąg z klatek',
    nameEn: 'Rack Pull',
    category: 'plecy',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Ustaw sztangę na klamrach na poziomie kolan lub ud. Pozycja jak w martwym ciągu, ale skrócony zakres ruchu. Pozwala używać większego ciężaru i skupia się na górnej fazie — mięśniach czworobocznych i lędźwiowych.',
  },
  {
    id: 'sumo-deadlift',
    name: 'Martwy ciąg sumo',
    nameEn: 'Sumo Deadlift',
    category: 'plecy',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Stań w szerokim rozkroku (1,5–2× szerokość bioder), palce stóp skierowane na zewnątrz. Chwyć sztangę wąskim chwytem między nogami. Otwórz biodra i wypchnij kolana na zewnątrz podczas unoszenia ciężaru.',
  },
  {
    id: 'inverted-row',
    name: 'Wiosłowanie australijskie',
    nameEn: 'Inverted Row',
    category: 'plecy',
    equipment: 'wolny',
    isCustom: false,
    description: 'Połóż się pod sztangą lub TRX, chwyć ją wyprostowanymi ramionami. Ciało w linii prostej, pięty na podłodze. Pociągnij klatkę do sztangi, prowadząc łokcie na boki. Opuść powoli. Im bardziej poziomo ciało, tym trudniej.',
  },
  {
    id: 'reverse-grip-pulldown',
    name: 'Ściąganie nachwytem odwróconym',
    nameEn: 'Reverse-Grip Pulldown',
    category: 'plecy',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Chwyć drążek wąskim podchwytem (dłonie skierowane do siebie/w twoją stronę). Ściągaj drążek do górnej klatki, łokcie prosto w dół przy ciele. Podchwyt angażuje bardziej dolną część najszerszych i bicepsy.',
  },
  {
    id: 'hyperextension',
    name: 'Wyprosty grzbietu',
    nameEn: 'Hyperextension',
    category: 'plecy',
    equipment: 'wolny',
    isCustom: false,
    description: 'Połóż się na ławce do hiperekstensi, biodra na krawędzi, nogi zablokowane. Opuść tułów w dół, następnie unieś go do linii z nogami lub lekko powyżej. Możesz trzymać talerz z ciężarem dla utrudnienia.',
  },
  {
    id: 'good-morning',
    name: 'Dzień dobry',
    nameEn: 'Good Morning',
    category: 'plecy',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Postaw sztangę na barkach jak do przysiadu. Przy napiętych, lekko ugiętych kolanach pochyl tułów do przodu aż jest prawie równoległy do podłogi, biodra cofnij. Wróć do pionu napinając pośladki i plecy.',
  },
  {
    id: 'close-grip-pulldown',
    name: 'Ściąganie wąskim chwytem',
    nameEn: 'Close-Grip Pulldown',
    category: 'plecy',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Użyj uchwytu V lub wąskiego drążka. Chwyć go podchwytem lub neutralnym i ściągaj do górnej klatki. Łokcie prowadź prosto w dół przy tułowiu. Wąski chwyt kładzie nacisk na dolną część najszerszych.',
  },

  // ─── NOGI ───────────────────────────────────────────────────────────────────
  {
    id: 'przysiad-sztanga',
    name: 'Przysiad ze sztangą',
    nameEn: 'Barbell Squat',
    category: 'nogi',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Sztanga na mięśniu czworobocznym (high bar) lub niżej (low bar). Stopy na szerokość bioder, palce lekko na zewnątrz. Zejdź z prostymi plecami do kąta ud przynajmniej równoległego do podłogi, kolana nad palcami. Wypchnij się do góry równomiernie.',
  },
  {
    id: 'przysiad-goblet',
    name: 'Przysiad goblet z hantlem',
    nameEn: 'Goblet Squat',
    category: 'nogi',
    equipment: 'hantle',
    isCustom: false,
    description: 'Trzymaj hantel oburącz przy klatce, pionowo. Stopy nieco szerzej niż biodra, palce na zewnątrz. Zejdź głęboko utrzymując hantel przy klatce i plecy proste. Kolana prowadź w kierunku palców. Dobre ćwiczenie na mobilność.',
  },
  {
    id: 'hip-thrust',
    name: 'Hip thrust ze sztangą',
    nameEn: 'Barbell Hip Thrust',
    category: 'nogi',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Oprzyj górną część pleców na ławce, sztanga na biodrach (z amortyzatorem). Stopy płasko na podłodze pod kolanami. Wypchnij biodra ku górze ściskając pośladki, aż uda są równoległe do podłogi. Przytrzymaj 1 sek. na górze.',
  },
  {
    id: 'wykroki-hantle',
    name: 'Wykroki z hantlami',
    nameEn: 'Dumbbell Lunges',
    category: 'nogi',
    equipment: 'hantle',
    isCustom: false,
    description: 'Stań prosto z hantlami przy bokach. Zrób duży krok do przodu, opuść tylne kolano niemal do podłogi. Przód kolana nad stopą, tułów pionowy. Wróć do pozycji startowej lub przejdź do przodu zmieniając nogi.',
  },
  {
    id: 'prostowanie-nog',
    name: 'Prostowanie nóg na maszynie',
    nameEn: 'Leg Extension',
    category: 'nogi',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Usiądź na maszynie, podkładka na poziomie kostek. Wyprostuj nogi do pełnego wyprostu, napinając czworogłowe. Przytrzymaj chwilę na górze, następnie opuść powoli. Nie używaj rozmachu. Ćwiczenie izoluje czworogłowe.',
  },
  {
    id: 'uginanie-nog',
    name: 'Uginanie nóg na maszynie',
    nameEn: 'Leg Curl',
    category: 'nogi',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Połóż się na maszynie, podkładka na wysokości dolnych łydek. Zegnij nogi przyciągając pięty do pośladków. Przytrzymaj chwilę i wróć powoli. Nie unoś bioder z podkładki. Izoluje mięśnie dwugłowe ud.',
  },
  {
    id: 'wspinanie-palce',
    name: 'Wspięcia na palce',
    nameEn: 'Calf Raise',
    category: 'nogi',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Stań na krawędzi stopnia z piętami w powietrzu (lub na maszynie). Unieś się na palcach jak najwyżej, ściskając łydki. Opuść pięty poniżej poziomu stopnia, czując rozciągnięcie. Ruch jest wolny i kontrolowany.',
  },
  {
    id: 'romanian-deadlift',
    name: 'Martwy ciąg rumuński',
    nameEn: 'Romanian Deadlift',
    category: 'nogi',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Stań ze sztangą, nogi prawie proste (lekko ugięte kolana). Przesuń biodra do tyłu opuszczając sztangę wzdłuż nóg, utrzymując plecy proste. Zejdź do momentu poczucia naciągnięcia mięśni dwugłowych, następnie wróć.',
  },
  {
    id: 'leg-press',
    name: 'Wypychanie nóg',
    nameEn: 'Leg Press',
    category: 'nogi',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Usiądź na maszynie, stopy na platformie na szerokość bioder. Zwolnij zamki i opuść platformę zginając kolana do kąta ok. 90°. Wypchnij platformę prostując nogi, nie blokując całkowicie kolan. Nie odrywaj pleców od oparcia.',
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Przysiad bułgarski',
    nameEn: 'Bulgarian Split Squat',
    category: 'nogi',
    equipment: 'hantle',
    isCustom: false,
    description: 'Oprzyj tylną stopę na ławce. Z hantlami w rękach opuść ciało w dół zginając przednią nogę w kolanie — do kąta ~90°. Przód kolana nad stopą. Wypchnij się do góry koncentrując na pracę pośladka i czworogłowego przedniej nogi.',
  },
  {
    id: 'nordic-curl',
    name: 'Uginanie nóg nordyckie',
    nameEn: 'Nordic Curl',
    category: 'nogi',
    equipment: 'wolny',
    isCustom: false,
    description: 'Klęknij, zablokuj stopy pod ławką lub z partnerem trzymającym kostki. Powoli opadaj tułowiem do przodu, hamując siłą mięśni dwugłowych ud — jak najwolniej. Przed uderzeniem w podłogę wróć do pionu. Bardzo intensywne dla dwugłowych.',
  },
  {
    id: 'front-squat',
    name: 'Przysiad ze sztangą z przodu',
    nameEn: 'Front Squat',
    category: 'nogi',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Sztanga opiera się na barkach z przodu, chwyt "clean" lub skrzyżowany. Tułów bardziej pionowy niż w klasycznym przysiadu. Zejdź głęboko, kolana mocno na zewnątrz. Wymaga dobrej mobilności nadgarstków i kostek.',
  },
  {
    id: 'step-up',
    name: 'Wchodzenie na skrzynię',
    nameEn: 'Step-Up',
    category: 'nogi',
    equipment: 'hantle',
    isCustom: false,
    description: 'Stań przed skrzynią lub ławką z hantlami w rękach. Wejdź na skrzynię jedną nogą, wyprostuj ją do pionu, wejdź drugą nogą. Schodź w odwrotnej kolejności. Ćwiczy równowagę i angażuje pośladki oraz czworogłowe asymetrycznie.',
  },
  {
    id: 'sissy-squat',
    name: 'Przysiad sissy',
    nameEn: 'Sissy Squat',
    category: 'nogi',
    equipment: 'wolny',
    isCustom: false,
    description: 'Stań trzymając się czegoś dla równowagi. Unieś pięty, zegnij kolana cofając je do przodu i jednocześnie odchyl tułów do tyłu — tworząc prostą linię od kolan przez biodra do barków. Intensywnie angażuje dolną część czworogłowych.',
  },
  {
    id: 'hip-abduction',
    name: 'Odwodzenie nóg na maszynie',
    nameEn: 'Hip Abduction Machine',
    category: 'nogi',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Usiądź na maszynie, nogi między podkładkami. Rozsuń nogi na zewnątrz, angażując odwodziciele biodra i mały pośladkowy. Wróć kontrolowanie, nie pozwalając ciężarowi kontrolować ruchu.',
  },
  {
    id: 'hip-adduction',
    name: 'Przywodzenie nóg na maszynie',
    nameEn: 'Hip Adduction Machine',
    category: 'nogi',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Usiądź z nogami po zewnętrznych stronach podkładek. Ściągnij nogi do siebie, angażując mięśnie przywodziciele. Wróć powoli do pozycji startowej. Szczególnie popularne dla wzmocnienia wewnętrznej strony ud.',
  },
  {
    id: 'donkey-calf-raise',
    name: 'Wspięcia na palce osiołek',
    nameEn: 'Donkey Calf Raise',
    category: 'nogi',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Stań na maszynie w pochyleniu z biodrami pod obciążeniem (lub z partnerem na dolnej części pleców). Pięty wolno opuść poniżej stopnia, następnie unieś się na palcach. Zgięcie w biodrach lepiej rozciąga mięsień brzuchaty łydki.',
  },

  // ─── NOGI (dodatkowe) ───────────────────────────────────────────────────────
  {
    id: 'hack-squat',
    name: 'Przysiad hack',
    nameEn: 'Hack Squat',
    category: 'nogi',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Wejdź na platformę maszyny hack squat, ramiona na uchwytach. Stopy na szerokość bioder, nieco wyżej na platformie. Zwolnij zamki i opuść ciało zginając kolana do kąta 90° lub głębiej. Wypchnij platformę prostując nogi. Angażuje intensywnie czworogłowe.',
  },
  {
    id: 'squat-smith-machine',
    name: 'Przysiad na Smith Machine',
    nameEn: 'Squat Smith Machine',
    category: 'nogi',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Ustaw sztangę Smitha na barkach. Stopy nieco wysunięte do przodu względem bioder (prowadnica jest pionowa). Zejdź z prostymi plecami do kąta ud równoległego do podłogi lub niżej. Wypchnij się do góry. Prowadnica wymaga innej mechaniki niż wolna sztanga.',
  },
  {
    id: 'lying-leg-curl',
    name: 'Uginanie nóg leżąc',
    nameEn: 'Lying Leg Curl',
    category: 'nogi',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Połóż się przodem na maszynie, podkładka na poziomie dolnych łydek. Zegnij nogi przyciągając pięty do pośladków. Biodra przyciśnięte do podkładki przez cały czas. Przytrzymaj chwilę na górze i wróć powoli. Izoluje mięśnie dwugłowe ud w pozycji leżącej.',
  },
  {
    id: 'seated-calf-raise-plate',
    name: 'Wspięcia na palce siedząc (plate loaded)',
    nameEn: 'Seated Calf Raise Plate Loaded',
    category: 'nogi',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Usiądź na maszynie z talerzami na kolanach lub na dedykowanej maszynie seated calf. Palce stóp na krawędzi stopnia, pięty wolno. Unieś się na palcach jak najwyżej ściskając łydki. Opuść pięty poniżej stopnia. Angażuje brzuchaty i płaszczkowaty łydki.',
  },
  {
    id: 'calf-press-seated-leg-press',
    name: 'Wspięcia na palce na leg press',
    nameEn: 'Calf Press on Seated Leg Press',
    category: 'nogi',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Na maszynie leg press oprzyj tylko przednią część stóp na dolnej krawędzi platformy (pięty w powietrzu). Wyprostuj nogi prawie całkowicie. Wykonuj wspięcia na palce wciskając platformę czubkami stóp, następnie wróć do rozciągnięcia łydek.',
  },
  {
    id: 'standing-calf-raise',
    name: 'Wspięcia na palce stojąc',
    nameEn: 'Standing Calf Raise',
    category: 'nogi',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Stań na maszynie do standing calf raise z ramionami pod poduszką. Palce stóp na krawędzi stopnia. Unieś pięty jak najwyżej, ściskając łydki w górnej pozycji przez 1 sekundę. Opuść powoli poniżej stopnia dla pełnego rozciągnięcia. Nogi lekko ugięte lub proste.',
  },

  // ─── BARKI ─────────────────────────────────────────────────────────────────
  {
    id: 'wyciskanie-zolnierskie',
    name: 'Wyciskanie żołnierskie sztangi',
    nameEn: 'Overhead Press',
    category: 'barki',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Stań ze sztangą na poziomie obojczyków, chwyt nieco szerszy niż barki. Wyciśnij sztangę nad głowę nie wyginając dolnego odcinka pleców. Głowa cofa się by sztanga mogła przejść, a następnie wraca pod sztangę. Napnij rdzeń przez cały czas.',
  },
  {
    id: 'wyciskanie-hantli-barki',
    name: 'Wyciskanie hantli nad głowę',
    nameEn: 'Dumbbell Shoulder Press',
    category: 'barki',
    equipment: 'hantle',
    isCustom: false,
    description: 'Usiądź lub stój z hantlami na poziomie barków, dłonie do przodu. Wyciśnij hantle nad głowę zbliżając je do siebie, nie stykając ich. Opuść powoli do pozycji startowej. Większy zakres ruchu niż ze sztangą.',
  },
  {
    id: 'unoszenie-boczne',
    name: 'Unoszenie hantli bokiem',
    nameEn: 'Lateral Raise',
    category: 'barki',
    equipment: 'hantle',
    isCustom: false,
    description: 'Stój z hantlami przy bokach. Unieś ramiona na boki do poziomu barków (małe palce lekko wyżej niż kciuki). Nie używaj rozmachu — ruch jest kontrolowany. Opuść powoli. Izoluje środkowe naramienne.',
  },
  {
    id: 'wznosy-przod',
    name: 'Wznosy hantli przed tułów',
    nameEn: 'Front Raise',
    category: 'barki',
    equipment: 'hantle',
    isCustom: false,
    description: 'Stój z hantlami przed udami. Unieś jedną lub obie ręce do przodu do poziomu barków. Ramiona prawie proste. Opuść powoli. Angażuje przednie naramienne, które i tak pracują przy większości ćwiczeń na klatkę.',
  },
  {
    id: 'arnold-press',
    name: 'Wyciskanie Arnolda',
    nameEn: 'Arnold Press',
    category: 'barki',
    equipment: 'hantle',
    isCustom: false,
    description: 'Zacznij z hantlami na poziomie klatki, dłonie ku sobie. Wyciśnij je obracając nadgarstki tak, by na górze dłonie były skierowane do przodu. Przy opuszczaniu wykonaj odwrót rotacji. Angażuje wszystkie trzy głowy naramiennych.',
  },
  {
    id: 'rear-delt-fly',
    name: 'Odwrotne rozpiętki',
    nameEn: 'Rear Delt Fly',
    category: 'barki',
    equipment: 'hantle',
    isCustom: false,
    description: 'Pochyl tułów do przodu ok. 45–90°. Trzymaj hantle opuszczone, lekko ugięte łokcie. Unieś ramiona na boki prowadząc łokcie ku górze i za plecy. Skup się na ściskaniu tylnych naramiennych i środkowego mięśnia czworobocznego.',
  },
  {
    id: 'upright-row',
    name: 'Wiosłowanie stojąc',
    nameEn: 'Upright Row',
    category: 'barki',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Chwyć sztangę lub hantle wąskim chwytem. Pociągnij ciężar wzdłuż ciała do góry, łokcie prowadząc ponad dłońmi. Zatrzymaj przy poziomie klatki lub brody. Opuść powoli. Angażuje naramienne i mięsień czworoboczny.',
  },
  {
    id: 'cable-lateral-raise',
    name: 'Unoszenie boczne na wyciągu',
    nameEn: 'Cable Lateral Raise',
    category: 'barki',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Stań bokiem do wyciągu dolnego, chwyć uchwyt ręką od strony maszyny. Unieś ramię na bok do poziomu barków. Wyciąg utrzymuje stałe napięcie przez cały zakres ruchu — przewaga nad hantlami.',
  },
  {
    id: 'machine-shoulder-press',
    name: 'Wyciskanie barków na maszynie',
    nameEn: 'Machine Shoulder Press',
    category: 'barki',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Dostosuj siedzisko tak, by uchwyty były na poziomie barków. Wyciśnij prosto do góry, nie blokując łokci całkowicie. Maszyna prowadzi ruch, co zmniejsza ryzyko kontuzji przy dużych obciążeniach.',
  },
  {
    id: 'scarecrow',
    name: 'Straszydło',
    nameEn: 'Scarecrow',
    category: 'barki',
    equipment: 'hantle',
    isCustom: false,
    description: 'Stój lub siedź, ramiona uniesione do boku równolegle do podłogi, łokcie zgięte 90° (pozycja jak litera L). Obracaj przedramiona do góry i do dołu utrzymując pozycję łokci. Wzmacnia rotatory zewnętrzne stawu barkowego.',
  },
  {
    id: 'band-pull-apart',
    name: 'Rozciąganie taśmy',
    nameEn: 'Band Pull-Apart',
    category: 'barki',
    equipment: 'wolny',
    isCustom: false,
    description: 'Trzymaj taśmę oporową oburącz przed sobą na poziomie klatki, ramiona wyprostowane. Rozciągnij taśmę rozchodząc ramiona na boki, ściskając łopatki. Wróć powoli. Świetne dla zdrowia stawów barkowych i tylnych naramiennych.',
  },

  // ─── BARKI (dodatkowe) ──────────────────────────────────────────────────────
  {
    id: 'face-pull-cable-floor',
    name: 'Ściąganie do twarzy wyciąg — siedząc na ziemi',
    nameEn: 'Face Pull Cable Seated on Floor',
    category: 'barki',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Usiądź na podłodze przed wyciągiem ustawionym na poziomie twarzy. Chwyć linę uchwytem neutralnym, łokcie na poziomie uszu. Ściągaj linę do twarzy rozchylając dłonie na zewnątrz. Pozycja siedząca eliminuje kompensację tułowiem i izoluje tylne naramienne.',
  },
  {
    id: 'front-raise-cable',
    name: 'Wznosy przed tułów na wyciągu',
    nameEn: 'Front Raise Cable',
    category: 'barki',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Stań przed wyciągiem dolnym, chwyć uchwyt jedną ręką. Unieś ramię do przodu do poziomu barków, prawie prosto. Wyciąg zapewnia stałe napięcie w dolnej fazie ruchu — przewaga nad hantlami. Opuść powoli. Angażuje przednie naramienne.',
  },
  {
    id: 'lateral-raise-machine',
    name: 'Unoszenie boczne na maszynie',
    nameEn: 'Lateral Raise Machine',
    category: 'barki',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Usiądź lub stań przy maszynie do lateral raise, ramiona na podpórkach lub uchwyty przy bokach. Unieś ramiona na boki do poziomu barków. Maszyna utrzymuje stałe napięcie przez cały zakres ruchu i eliminuje podrywanie. Opuść kontrolowanie.',
  },
  {
    id: 'reverse-fly-machine',
    name: 'Odwrotne rozpiętki na maszynie',
    nameEn: 'Reverse Fly Machine',
    category: 'barki',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Usiądź przy maszynie pec-deck odwrócony (twarzą do podkładki) lub przy maszynie reverse fly. Uchwyty przed sobą, lekko ugięte łokcie. Rozsuń ramiona na boki i do tyłu ściskając tylne naramienne i środkowy czworoboczny. Wróć powoli.',
  },
  {
    id: 'shrug-dumbbell',
    name: 'Wzruszanie ramionami z hantlami',
    nameEn: 'Shrug Dumbbell',
    category: 'barki',
    equipment: 'hantle',
    isCustom: false,
    description: 'Stój z hantlami wzdłuż ciała, chwyt neutralny. Unieś barki prosto do góry starając się dotknąć nimi uszu. Nie obracaj ramionami — ruch jest czysto pionowy. Przytrzymaj na górze 1 sekundę ściskając czworoboczny. Opuść powoli. Hantle pozwalają na naturalniejszy ruch niż sztanga.',
  },

  // ─── BICEPS ─────────────────────────────────────────────────────────────────
  {
    id: 'uginanie-hantli-biceps',
    name: 'Uginanie hantli na biceps',
    nameEn: 'Dumbbell Bicep Curl',
    category: 'biceps',
    equipment: 'hantle',
    isCustom: false,
    description: 'Stój z hantlami przy bokach, dłonie do przodu. Zegnij łokcie unosząc hantle do barków, obracając nadgarstki supinacyjnie. Łokcie trzymaj przy ciele. Opuść powoli do pełnego wyprostu. Nie używaj tułowia.',
  },
  {
    id: 'uginanie-sztangi-biceps',
    name: 'Uginanie sztangi na biceps',
    nameEn: 'Barbell Bicep Curl',
    category: 'biceps',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Stój ze sztangą podchwytem na szerokość barków. Ugnij łokcie unosząc sztangę do klatki. Łokcie przy tułowiu przez cały ruch. Opuść powoli do pełnego wyprostu. Pozwala używać większego ciężaru niż przy hantlach.',
  },
  {
    id: 'hammer-curl',
    name: 'Uginanie hantli młotkowe',
    nameEn: 'Hammer Curl',
    category: 'biceps',
    equipment: 'hantle',
    isCustom: false,
    description: 'Trzymaj hantle chwytem neutralnym (kciuki do góry). Ugnij łokcie unosząc hantle, dłonie przez cały czas skierowane do siebie. Angażuje silniej ramienno-promieniowy i głowę długą bicepsa. Szersze ćwiczenie na ramię.',
  },
  {
    id: 'preacher-curl',
    name: 'Uginanie na modlitewniku',
    nameEn: 'Preacher Curl',
    category: 'biceps',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Oprzyj ramiona na pochyłej podpórce modlitewnika. Chwyć EZ-bar lub hantlę. Ugnij łokcie unosząc ciężar. Podkładka eliminuje możliwość oszustwa i izoluje bicepsa. Skup się na pełnym wyproście i powolnym opuszczaniu.',
  },
  {
    id: 'concentration-curl',
    name: 'Uginanie izolowane',
    nameEn: 'Concentration Curl',
    category: 'biceps',
    equipment: 'hantle',
    isCustom: false,
    description: 'Usiądź, łokieć oparty o wewnętrzną część uda. Ugnij łokieć unosząc hantel do barku. Pełna izolacja jednego ramienia. Skup się na szczytowym skurczu i powolnym opuszczaniu. Zmień rękę po zakończeniu serii.',
  },
  {
    id: 'cable-curl',
    name: 'Uginanie na wyciągu',
    nameEn: 'Cable Curl',
    category: 'biceps',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Stań przy wyciągu dolnym, chwyć drążek prostym lub EZ. Ugnij łokcie unosząc drążek do klatki. Wyciąg utrzymuje stałe napięcie w dolnej pozycji — przewaga nad hantlami. Łokcie nieruchome przy tułowiu.',
  },
  {
    id: 'incline-dumbbell-curl',
    name: 'Uginanie na ławce skośnej',
    nameEn: 'Incline Dumbbell Curl',
    category: 'biceps',
    equipment: 'hantle',
    isCustom: false,
    description: 'Usiądź na pochylonej ławce (45–60°) opierając plecy. Ramiona zwisają swobodnie za ławką. Ugnij łokcie supinując nadgarstki. Pozycja skośna wydłuża zakres ruchu i mocniej rozciąga głowę długą bicepsa.',
  },
  {
    id: 'zottman-curl',
    name: 'Uginanie Zottmana',
    nameEn: 'Zottman Curl',
    category: 'biceps',
    equipment: 'hantle',
    isCustom: false,
    description: 'Ugnij hantle podchwytem jak w normalnym uginaniu. Na górze obróć nadgarstki tak, by dłonie były skierowane w dół. Opuść hantle nachwytem. Na dole wróć do podchwytu. Łączy pracę bicepsa (w górę) i ramienno-promieniowego (w dół).',
  },
  {
    id: 'hammer-curl-cable',
    name: 'Uchwyt młotkowy na wyciągu',
    nameEn: 'Hammer Curl Cable',
    category: 'biceps',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Stań przy wyciągu dolnym, chwyć uchwyt linowy chwytem neutralnym (kciuki do góry). Ugnij łokcie unosząc ręce do barków, dłonie przez cały ruch skierowane do siebie. Wyciąg zapewnia stałe napięcie w całym zakresie.',
  },
  {
    id: 'hammer-curl-modlitownik',
    name: 'Uchwyt młotkowy na modlitowniku',
    nameEn: 'Hammer Curl Preacher',
    category: 'biceps',
    equipment: 'hantle',
    isCustom: false,
    description: 'Oprzyj ramiona na pochyłej podpórce modlitewnika, trzymaj hantlę chwytem neutralnym (kciuk do góry). Ugnij łokieć izolując ramię. Modlitownik eliminuje oszukiwanie i skupia pracę na bicepsie i ramienno-promieniowym.',
  },
  {
    id: 'bayesian-curl',
    name: 'Bayesian curl',
    nameEn: 'Bayesian Curl',
    category: 'biceps',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Stań tyłem do wyciągu dolnego trzymając uchwyt za plecami (ramię lekko cofnięte). Ugnij łokieć unosząc hantel do barku. Pozycja z ramieniem za tułowiem maksymalnie rozciąga głowę długą bicepsa i zwiększa zakres ruchu.',
  },
  {
    id: 'preacher-curl-dumbbell',
    name: 'Uginanie na modlitowniku z hantlą',
    nameEn: 'Preacher Curl Dumbbell',
    category: 'biceps',
    equipment: 'hantle',
    isCustom: false,
    description: 'Oprzyj jedno ramię na pochyłej podpórce modlitewnika, trzymaj hantlę podchwytem. Ugnij łokieć unosząc hantlę. Modlitownik unieruchamia ramię eliminując angaż tułowia. Ćwiczenie unilateralne pozwala skupić się na każdym ramieniu osobno.',
  },
  {
    id: 'preacher-curl-machine',
    name: 'Uginanie na modlitowniku na maszynie',
    nameEn: 'Preacher Curl Machine',
    category: 'biceps',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Usiądź na maszynie modlitewnikowej, oprzyj ramiona na podkładce. Ugnij łokcie chwytem podchwytowym. Maszyna utrzymuje stałe napięcie i idealną tor ruchu, co pozwala skupić się na izolacji bicepsa bez ryzyka kontuzji.',
  },
  {
    id: 'reverse-curl-barbell',
    name: 'Uginanie odwrócone ze sztangą',
    nameEn: 'Reverse Curl Barbell',
    category: 'biceps',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Chwyć sztangę nachwytem (dłonie skierowane w dół). Ugnij łokcie unosząc sztangę do klatki, łokcie przy tułowiu. Angażuje ramienno-promieniowy i brachialis silniej niż zwykłe uginanie. Wzmacnia również prostowniki nadgarstka.',
  },
  {
    id: 'reverse-curl-dumbbell',
    name: 'Uginanie odwrócone z hantlami',
    nameEn: 'Reverse Curl Dumbbell',
    category: 'biceps',
    equipment: 'hantle',
    isCustom: false,
    description: 'Chwyć hantle nachwytem (dłonie skierowane w dół). Ugnij łokcie unosząc hantle do barków, łokcie przy tułowiu. Hantle pozwalają na niezależną pracę każdego ramienia. Angażuje ramienno-promieniowy i brachialis.',
  },
  {
    id: 'reverse-curl-cable',
    name: 'Uginanie odwrócone na wyciągu',
    nameEn: 'Reverse Curl Cable',
    category: 'biceps',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Stań przy wyciągu dolnym, chwyć drążek prostym nachwytem. Ugnij łokcie unosząc drążek do klatki. Wyciąg zapewnia stałe napięcie i wymusza kontrolowany ruch. Skutecznie angażuje ramienno-promieniowy i brachialis.',
  },

  // ─── TRICEPS ─────────────────────────────────────────────────────────────────
  {
    id: 'francuskie-wyciskanie',
    name: 'Francuskie wyciskanie hantlem',
    nameEn: 'Skull Crusher',
    category: 'triceps',
    equipment: 'hantle',
    isCustom: false,
    description: 'Połóż się na ławce, trzymaj hantle (lub EZ-bar) wyprostowanymi ramionami nad klatką. Zegnij łokcie opuszczając ciężar do czoła lub za głowę. Wyciśnij z powrotem trzymając łokcie nieruchomo. Izoluje tricepsy.',
  },
  {
    id: 'wyciskanie-wyciag-dol',
    name: 'Wyciskanie na wyciągu w dół',
    nameEn: 'Tricep Pushdown',
    category: 'triceps',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Stań przy wyciągu górnym, chwyć drążek lub linę. Łokcie przy tułowiu, wypchnij drążek w dół do pełnego wyprostu tricepsów. Przytrzymaj 1 sekundę ściskając tricepsy. Wróć powoli. Łokcie pozostają nieruchome przez cały ruch.',
  },
  {
    id: 'dipsy-porecze',
    name: 'Dipsy na poręczach',
    nameEn: 'Tricep Dips',
    category: 'triceps',
    equipment: 'wolny',
    isCustom: false,
    description: 'Chwyć poręcze tułowiem pionowym. Trzymaj ciało prosto (nie pochylaj do przodu jak przy Chest Dips). Zegnij łokcie opuszczając ciało, następnie wyciśnij do góry. Tułów pionowy skupia obciążenie na tricepsach.',
  },
  {
    id: 'close-grip-bench',
    name: 'Wyciskanie wąskim chwytem',
    nameEn: 'Close-Grip Bench Press',
    category: 'triceps',
    equipment: 'sztanga',
    isCustom: false,
    description: 'Połóż się na ławce, chwyć sztangę na szerokość barków (nie wążej — stresuje to nadgarstki). Opuść ją do klatki trzymając łokcie blisko tułowia. Wyciśnij do góry. Tricepsy pracują znacznie bardziej niż klatka.',
  },
  {
    id: 'overhead-tricep-ext',
    name: 'Prostowanie trójgłowego nad głową',
    nameEn: 'Overhead Tricep Extension',
    category: 'triceps',
    equipment: 'hantle',
    isCustom: false,
    description: 'Trzymaj hantel lub EZ-bar nad głową wyprostowanymi ramionami. Zegnij łokcie opuszczając ciężar za głowę. Łokcie skierowane ku górze, nieruchome. Wyciśnij do góry. Rozciąga głowę długą tricepsa bardziej niż ćwiczenia przy tułowiu.',
  },
  {
    id: 'tricep-kickback',
    name: 'Odpychanie hantla w tył',
    nameEn: 'Tricep Kickback',
    category: 'triceps',
    equipment: 'hantle',
    isCustom: false,
    description: 'Pochyl tułów równolegle do podłogi, ramię górne przy tułowiu. Wyciśnij hantel do pełnego wyprostu łokcia cofając przedramię do tyłu. Przytrzymaj chwilę. Opuść powoli. Ważne by ramię górne pozostało nieruchome.',
  },
  {
    id: 'diamond-push-up',
    name: 'Pompki diament',
    nameEn: 'Diamond Push-Up',
    category: 'triceps',
    equipment: 'wolny',
    isCustom: false,
    description: 'Przyjmij pozycję pompki z dłońmi blisko siebie tworząc trójkąt (diament) pod klatką. Opuść klatkę do dłoni trzymając łokcie blisko ciała. Wypchnij do góry. Intensywnie angażuje wszystkie trzy głowy tricepsa.',
  },
  {
    id: 'cable-overhead-tricep',
    name: 'Prostowanie tricepsa na wyciągu nad głową',
    nameEn: 'Cable Overhead Tricep Extension',
    category: 'triceps',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Stań przed wyciągiem górnym tyłem lub z boku, chwyć linę za głową. Wyprostuj ramiona nad głową. Wyciąg utrzymuje stałe napięcie w rozciągniętej pozycji — szczególnie korzystne dla głowy długiej tricepsa.',
  },

  // ─── BRZUCH ─────────────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    nameEn: 'Plank',
    category: 'brzuch',
    equipment: 'wolny',
    isCustom: false,
    description: 'Oprzyj się na przedramionach i palcach stóp. Ciało w idealnej linii prostej — biodra nie opadają ani nie unoszą się. Napnij brzuch, pośladki i czworogłowe. Oddychaj równomiernie. Utrzymaj pozycję przez ustalony czas.',
  },
  {
    id: 'brzuszki-maszyna',
    name: 'Brzuszki na maszynie',
    nameEn: 'Cable Crunch',
    category: 'brzuch',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Klęknij przed wyciągiem górnym z liną przy głowie. Zegnij tułów w dół ściągając łokcie do kolan, skupiając ruch na brzuchu (nie na biodrach). Wróć do pionu kontrolowanie. Lina przy skroniach przez cały czas.',
  },
  {
    id: 'unoszenie-nog-zwis',
    name: 'Unoszenie nóg w zwisie',
    nameEn: 'Hanging Leg Raise',
    category: 'brzuch',
    equipment: 'wolny',
    isCustom: false,
    description: 'Zwis na drążku, ramiona proste. Unieś nogi do poziomu bioder (prostymi) lub wyżej (z zaokrąglaniem pleców). Opuść powoli nie dopuszczając do kiwania. Angażuje dolną część prostego brzucha i zginacze bioder.',
  },
  {
    id: 'russian-twist',
    name: 'Skręty tułowia',
    nameEn: 'Russian Twist',
    category: 'brzuch',
    equipment: 'wolny',
    isCustom: false,
    description: 'Usiądź z nogami uniesionymi i kolanami lekko ugiętymi, tułów odchylony ok. 45°. Skręcaj tułów na boki, dotykając rękami lub talerzem podłogi po każdej stronie. Utrzymuj napięcie brzucha przez cały czas.',
  },
  {
    id: 'ab-rollout',
    name: 'Rollout kółkiem',
    nameEn: 'Ab Rollout',
    category: 'brzuch',
    equipment: 'wolny',
    isCustom: false,
    description: 'Klęknij trzymając kółko ab-roller pod ramionami. Powoli toczysz kółko do przodu, prostując ciało ku podłodze. Zatrzymaj przed upadkiem, a następnie napnij brzuch i wróć do klęku. Jedno z najtrudniejszych ćwiczeń na rdzeń.',
  },
  {
    id: 'side-plank',
    name: 'Plank boczny',
    nameEn: 'Side Plank',
    category: 'brzuch',
    equipment: 'wolny',
    isCustom: false,
    description: 'Połóż się na boku, oprzyj na przedramieniu i krawędzi stopy. Unieś biodra tworząc prostą linię od głowy do stóp. Napnij boczne mięśnie brzucha (skośne). Utrzymaj pozycję, następnie zmień stronę.',
  },
  {
    id: 'bicycle-crunch',
    name: 'Brzuszki rowerowe',
    nameEn: 'Bicycle Crunch',
    category: 'brzuch',
    equipment: 'wolny',
    isCustom: false,
    description: 'Połóż się na plecach, ręce za głową. Unieś nogi i naprzemiennie przyciągaj każde kolano do przeciwnego łokcia skręcając tułów. Ćwiczenie angażuje prosty i skośne mięśnie brzucha jednocześnie.',
  },
  {
    id: 'dragon-flag',
    name: 'Dragon flag',
    nameEn: 'Dragon Flag',
    category: 'brzuch',
    equipment: 'wolny',
    isCustom: false,
    description: 'Połóż się na ławce, chwyć ją za głową. Unieś całe ciało w pozycji pionowej, podpierając się na barkach. Powoli opuść ciało w linii prostej, nie dopuszczając do dotknięcia ławki. Wróć powoli. Ekstremalnie trudne ćwiczenie rdzenia.',
  },
  {
    id: 'mountain-climber',
    name: 'Wspinaczka',
    nameEn: 'Mountain Climber',
    category: 'brzuch',
    equipment: 'wolny',
    isCustom: false,
    description: 'Przyjmij pozycję pompki. Dynamicznie przyciągaj naprzemiennie kolana do klatki piersiowej, jakbyś biegł w miejscu w pozycji poziomej. Brzuch napięty, biodra nie unoszą się. Angażuje rdzeń i podnosi tętno.',
  },
  {
    id: 'knee-raise-captains-chair',
    name: 'Uginanie kolan w poręczach',
    nameEn: "Knee Raise (Captain's Chair)",
    category: 'brzuch',
    equipment: 'wolny',
    isCustom: false,
    description: 'Stań na krześle kapitańskim opierając przedramiona na podłokietnikach, plecy przyciśnięte do oparcia. Ugnij kolana unosząc je do klatki piersiowej, następnie opuść kontrolowanie. Angażuje prostą brzucha i biodrowo-lędźwiowy.',
  },
  {
    id: 'hanging-knee-raise',
    name: 'Uginanie kolan w zwisie',
    nameEn: 'Hanging Knee Raise',
    category: 'brzuch',
    equipment: 'wolny',
    isCustom: false,
    description: 'Zawis na drążku nachwytem lub podchwytem. Ugnij kolana unosząc je do klatki piersiowej, lekko zaginając miednicę do tyłu. Opuść nogi kontrolowanie bez bujania. Trudniejsza wersja — uginanie prostych nóg jeszcze bardziej angażuje brzuch.',
  },

  // ─── PLECY (dodatkowe) ──────────────────────────────────────────────────────
  {
    id: 'bent-over-row-dumbbell',
    name: 'Wiosłowanie hantlami oburącz',
    nameEn: 'Bent Over Row Dumbbell',
    category: 'plecy',
    equipment: 'hantle',
    isCustom: false,
    description: 'Pochyl tułów do przodu ok. 45°, kolana lekko ugięte, hantle zwisają prosto w dół. Pociągnij obie hantle jednocześnie do brzucha ściskając łopatki. Łokcie idą blisko tułowia. Opuść kontrolowanie do pełnego wyprostu. Angażuje cały środkowy grzbiet symetrycznie.',
  },
  {
    id: 'iso-lateral-row-plate',
    name: 'Wiosłowanie Iso Lateral plate loader',
    nameEn: 'Iso Lateral Row Plate Loader',
    category: 'plecy',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Usiądź na maszynie Iso Lateral Row z obciążeniem na wysięgnikach. Każde ramię pracuje niezależnie — pozwala na pełny zakres ruchu i wyrównanie siły obu stron. Pociągnij uchwyty do boków klatki ściskając łopatki, wróć z kontrolą.',
  },
  {
    id: 'incline-row-dumbbell',
    name: 'Wiosłowanie hantlami na ławce skośnej',
    nameEn: 'Incline Row Dumbbell',
    category: 'plecy',
    equipment: 'hantle',
    isCustom: false,
    description: 'Oprzyj klatkę na pochylonej ławce (kąt 30–45°) twarzą w dół. Trzymaj hantle pionowo. Pociągnij je do boków, prowadząc łokcie ku górze i na zewnątrz. Klatka przy ławce przez cały czas eliminuje angaż tułowia i izoluje środkowy grzbiet.',
  },
  {
    id: 'iso-lateral-row-machine',
    name: 'Wiosłowanie Iso Lateral na maszynie',
    nameEn: 'Iso Lateral Row Machine',
    category: 'plecy',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Maszyna Iso Lateral Row z elektrycznie niezależnymi ramionami. Usiądź, klatka na podpórce, chwyć uchwyty. Ciągnij każde ramię niezależnie lub naprzemiennie do klatki. Idealna izolacja środkowego grzbietu bez kompensacji słabszą stroną.',
  },
  {
    id: 'lat-pulldown-machine',
    name: 'Ściąganie drążka na maszynie',
    nameEn: 'Lat Pulldown Machine',
    category: 'plecy',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Maszyna do lat pulldown z prowadnicą (nie wyciąg kablowy). Usiądź, uda pod poduszką, chwyć uchwyty. Ściągaj ramiona w dół i do tyłu, łopatki w dół, łokcie prowadź ku boksom ciała. Prowadnica zapewnia stałą trajektorię ruchu.',
  },
  {
    id: 'lat-pulldown-single-arm',
    name: 'Ściąganie drążka jedną ręką',
    nameEn: 'Lat Pulldown Single Arm',
    category: 'plecy',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Usiądź przy wyciągu, chwyć jedną ręką uchwyt kablowy. Ściągaj ramię w dół i do boku klatki, rotując lekko tułów ku ściąganemu ramieniu. Wróć do pełnego wyprostu. Pozwala na większy zakres ruchu i likwiduje dysproporcje sił między stronami.',
  },

  // ─── CARDIO ─────────────────────────────────────────────────────────────────
  {
    id: 'bieznia',
    name: 'Bieżnia',
    nameEn: 'Treadmill',
    category: 'cardio',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Bieg lub marsz na bieżni. Ustaw prędkość i nachylenie. Dla spalania tłuszczu skuteczny jest marsz pod górę (nachylenie 8–15°). Bieg interwałowy (np. 30 sek. sprint / 60 sek. marsz) jest efektywniejszy niż stały jednostajny bieg.',
  },
  {
    id: 'orbitrek',
    name: 'Orbitrek',
    nameEn: 'Elliptical',
    category: 'cardio',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Ćwiczenie cardio o niskim wpływie na stawy. Angażuje jednocześnie górę i dół ciała. Utrzymuj wyprostowaną postawę i napięty rdzeń. Zmiana kierunku (jazda do tyłu) angażuje inne partie mięśniowe.',
  },
  {
    id: 'rowerek-stacjonarny',
    name: 'Rowerek stacjonarny',
    nameEn: 'Stationary Bike',
    category: 'cardio',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Ustaw siodełko tak, by przy wyprostowanej nodze na pedale kolano było lekko zgięte. Możesz trenować stałe cardio lub HIIT (np. 20 sek. max effort / 40 sek. spokojnie). Mały wpływ na stawy, świetne dla regeneracji.',
  },
  {
    id: 'rowing-machine',
    name: 'Wioślarz',
    nameEn: 'Rowing Machine',
    category: 'cardio',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Ruch składa się z 4 faz: odbicie nogami (60%), pochylenie tułowia (20%), pociągnięcie rąk (20%). Przy odbijaniu nogi są pierwsze — nie ciągnij ramionami gdy nogi jeszcze pracują. Angażuje ~86% mięśni ciała.',
  },
  {
    id: 'jump-rope',
    name: 'Skakanka',
    nameEn: 'Jump Rope',
    category: 'cardio',
    equipment: 'wolny',
    isCustom: false,
    description: 'Skacz na palcach, minimalne odbicia od podłogi. Łokcie przy ciele, ruch nadgarstkami kręci skakanką. Zacznij od bloków 30 sek., stopniowo wydłużaj. Podwójna skakanka (double-under) wymaga wyższego skoku i szybszego kręcenia.',
  },
  {
    id: 'narciarz',
    name: 'Narciarz (Ski Erg)',
    nameEn: 'Ski Erg',
    category: 'cardio',
    equipment: 'maszyna',
    isCustom: false,
    description: 'Stań przed maszyną Ski Erg, chwyć uchwyty nad głową. Pociągnij je dynamicznie w dół i za biodra wykonując ruch narciarza (stok zjazdowy). Wróć do góry kontrolowanie. Angażuje mięśnie brzucha, najszersze grzbietu, ramiona i tricepsy. Świetne cardio z niskim wpływem na stawy.',
  },
];
